server:
  port: 8004
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eu7001.com:7001/eureka/,http://eu7002.com:7002/eureka/,http://eu7003.com:7003/eureka/
    register-with-eureka: true
    fetch-registry: true
