server:
  port: 7003
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eu7003.com
  client:
    service-url:
      defaultZone: http://eu7001.com:7001/eureka/,http://eu7002.com:7002/eureka/
    register-with-eureka: false
    fetch-registry: false