server:
  port: 7001
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eu7001.com
  client:
    service-url:
      defaultZone: http://eu7002.com:7002/eureka/,http://eu7003.com:7003/eureka/
    register-with-eureka: false
    fetch-registry: false